#!/bin/sh /etc/rc.common

. /etc/functions.sh

start() {
        local userpwd
	local supportpwd
	local adminpwd
	local rootpwd

	config_load passwords
	config_get userpwd user password
	config_get supportpwd support password
	config_get adminpwd admin password
	config_get rootpwd root password

	[ -n "$userpwd" ] && (echo $userpwd; sleep 1; echo $userpwd) | passwd user >/dev/null 2>&1
        [ -n "$supportpwd" ] && (echo $supportpwd; sleep 1; echo $supportpwd) | passwd support >/dev/null 2>&1
        [ -n "$adminpwd" ] && (echo $adminpwd; sleep 1; echo $adminpwd) | passwd admin >/dev/null 2>&1
        [ -n "$rootpwd" ] && (echo $rootpwd; sleep 1; echo $rootpwd) | passwd root >/dev/null 2>&1
        
	uci delete passwords.user.password >/dev/null 2>&1
	uci delete passwords.support.password >/dev/null 2>&1
	uci delete passwords.admin.password >/dev/null 2>&1
	uci delete passwords.root.password >/dev/null 2>&1
	uci commit
}
