#!/bin/sh /etc/rc.common

START=15

. /lib/functions.sh

get_port_no() {
	local ports="0 1 2 3 4 5 6 7"
	local port="$1"
	local ifname

	for p in $ports; do
		ifname="$(ethswctl getifname $p | awk '{print$NF}')"
		if [ "$ifname" == "$port" ]; then
			echo "$p"
			break
		fi
	done
}

get_current_speed() {
	local port="$1"
	local media="$(ethctl $port media-type 2>&1)"
	if echo $media | grep "Auto-negotiation enabled" >/dev/null; then
		echo "auto"
	elif echo $media | grep "100 mbps, full-duplex" >/dev/null; then
		echo "100FD"
	elif echo $media | grep "100 mbps, half-duplex" >/dev/null; then
		echo "100HD"
	elif echo $media | grep "10 mbps, full-duplex" >/dev/null; then
		echo "10FD"
	elif echo $media | grep "10 mbps, half-duplex" >/dev/null; then
		echo "10HD"
	fi
}

set_port_speed() {
	local port="$1"
	local speed="$2"
	local curspeed=$(get_current_speed $port)
	local portno

	ifconfig $port >/dev/null 2>&1 || return

	if [ "$speed" != "$curspeed" ]; then
		case "$speed" in
			1000*)
				portno=$(get_port_no $port)
				case "$speed" in
					1000FD) ethswctl -c phymode -p $portno -y 1000 -z 1 ;;
					1000HD) ethswctl -c phymode -p $portno -y 1000 -z 0 ;;
				esac
			;;
			10*)
				ethctl $port media-type $speed
			;;
			*)
				ethctl $port media-type auto
			;;
		esac
	fi
}

configure_ethports() {
	config_get eth0 "$1" eth0
	set_port_speed eth0 $eth0
	
	config_get eth1 "$1" eth1
	set_port_speed eth1 $eth1
	
	config_get eth2 "$1" eth2
	set_port_speed eth2 $eth2
	
	config_get eth3 "$1" eth3
	set_port_speed eth3 $eth3
	
	config_get eth4 "$1" eth4
	set_port_speed eth4 $eth4
}

start() {
	config_load ports
	config_foreach configure_ethports ethports
}

restart() {
        start
}

