#!/bin/sh

local hexfile="$1"
local decfile="$2"
local lined=""
local cnt=0
[ -f $decfile ] && rm -f $decfile

while read line
do
	lcnt=$((cnt+1))
        for i in $line; do
                cnt=$((cnt+1))
		case $i in
			0x*)
				case $cnt in
					7|9|11)
						i=$(printf '%d.%d.%d.%d\n' `echo ${i:2:8} | sed -r 's/(..)/0x\1 /g'`)
					;;
					*)
						if [ "$i" = "0xffffffff" ]; then
							i="-1"
						else
							i=$(printf '%d' $i)
						fi
					;;
				esac
			;;
		esac
		case $line in
			*snooping*)
				printf "%s" "$i" > /var/newigmpsnpi
			;;
			*)
				case $cnt in
					5|6)
						[ $(expr length "$i") -gt 7 ] && printf "%-20s %s" "$i" > /var/newigmpsnpi || printf "%-8s %s" "$i" > /var/newigmpsnpi
					;;
					7|9|11)
						printf "%-20s %s" "$i" > /var/newigmpsnpi
					;;
		                        *)
		                                printf "%-8s %s" "$i" > /var/newigmpsnpi
		                        ;;
				esac
			;;
		esac
		printf "%s\t" "$(cat /var/newigmpsnpi)" > /var/newigmpsnpi
		printf "%s%s" "$(cat /var/newigmpsnpline 2>/dev/null)" "$(cat /var/newigmpsnpi)" > /var/newigmpsnpline
		rm /var/newigmpsnpi
        done
        cnt=0
        printf "%s\n" "$(cat /var/newigmpsnpline)" >> $decfile
        rm /var/newigmpsnpline
done < $hexfile

