#!/bin/sh

/etc/init.d/ipsec enabled && {
	/etc/init.d/ipsec stop
	/etc/init.d/ipsec disable
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ipsec[-1]
	add ucitrack ipsec
	set ucitrack.@ipsec[-1].init=ipsec
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
