#!/bin/sh /etc/rc.common
#
# Copyright (C) 2015 inteno.org
#

. /lib/functions.sh
START=71

start() {
	local enable=0
        local filter=0
        

        config_load catv
        config_get enable catv enable
        config_get filter catv filter
	ubus call catv set-enable "{\"enable\":\"$enable\"}"
	ubus call catv set-filter "{\"filter\":\"$filter\"}"

}
