#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@power_mgmt[-1]
	add ucitrack power_mgmt
	set ucitrack.@power_mgmt[-1].init=power_mgmt
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
