#!/bin/sh /etc/rc.common

. /lib/functions.sh
. /usr/share/libubox/jshn.sh
. /usr/lib/ddns/dynamic_dns_functions.sh

START=27

dynamic_ddns() {
        local interface up

        config_get interface $1 interface
        json_load "$(ifstatus $interface)"
        json_get_var up up
        if [ "$up" == "1" ]; then
                start_daemon_for_all_ddns_sections $interface
        fi
}

start() {}

restart() {   
        config_load ddns
        config_foreach dynamic_ddns service
}
