#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@passwords[-1]
	add ucitrack passwords
	set ucitrack.@passwords[-1].init=passwords_update
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
