#!/bin/sh
CHECKSUMS=/etc/configchecksums
echo "$CHECKSUMS" >> /etc/sysupgrade.conf 
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@provisioning[-1]
	add ucitrack provisioning
	set ucitrack.@provisioning[-1].init=iup
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
